<script setup lang="ts">
import { useStore } from 'vuex';

import type { RootState } from '~/store';

useHead({
  title: 'Главная',
  meta: [{ name: 'description', content: 'Главная страница' }]
});

const features = [
  {
    id: 1,
    title: 'Instant Analysis',
    subTitle: 'Results in seconds',
    iconName: 'Z'
  },
  {
    id: 2,
    title: '99% Accuracy',
    subTitle: 'Reliable detection',
    iconName: 'A'
  },
  {
    id: 3,
    title: 'Any Text Length',
    subTitle: 'No limitations',
    iconName: 'N'
  }
];

const store = useStore<RootState>();

const resultRef = ref<HTMLElement | null>(null);

const analyzeText = computed({
  get: () => store.state.detector?.currentText || '',
  set: (value: string) => {
    store.commit('detector/SET_TEXT', value);
  }
});

const analyzeResult = computed(() => {
  return store.state.detector?.result;
});

const analyzeIsLoading = computed(() => !!store.state.detector?.loading);

function handleAnalyze() {
  store.dispatch('detector/analyzeText');

  nextTick(() => {
    if (resultRef.value) {
      const element = resultRef.value.$el || resultRef.value;

      element.scrollIntoView({
        behavior: 'smooth',
        block: 'start'
      });
    }
  });
}
</script>

<template>
  <div class="mx-auto max-w-4xl relative">
    <div class="mb-12 text-center">
      <Idk class="mb-4" text="AI-Powered Detection" />
      <h1 class="mb-4 text-balance text-4xl font-bold tracking-tight text-foreground md:text-5xl lg:text-6xl">
        AI Content <span class="text-primary">Detector</span>
      </h1>
      <p class="mx-auto max-w-2xl text-pretty text-lg text-muted-foreground">
        Analyze any text to determine if it was written by a human or generated by AI. Get instant, accurate results
        with our advanced detection algorithm.
      </p>
    </div>
    <div class="mb-10 grid grid-cols-1 gap-4 sm:grid-cols-3">
      <div
        v-for="feature in features"
        :key="feature.id"
        class="flex items-center gap-3 rounded-lg border border-border bg-card p-4"
      >
        <Icon :icon-name="feature.iconName" ui="dark" />
        <div>
          <p class="font-medium text-foreground">{{ feature.title }}</p>
          <p class="text-sm text-muted-foreground">{{ feature.subTitle }}</p>
        </div>
      </div>
    </div>
    <TextAreaField v-model="analyzeText" @analyze="handleAnalyze" />
    <Transition name="slide-up">
      <BaseResult
        v-if="analyzeIsLoading || analyzeResult"
        ref="resultRef"
        :result="analyzeResult"
        :is-loading="analyzeIsLoading"
      />
    </Transition>
  </div>
</template>

<style scoped>
.slide-up-enter-active {
  transition: all 0.8s cubic-bezier(0.16, 1, 0.3, 1);
}

.slide-up-enter-from {
  opacity: 0;
  transform: translateY(40px) scale(0.98);
}
</style>
