version: '3.8'

services:
  # 1. ФРОНТЕНД
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8080/api/v1
    depends_on:
      - backend

  # 2. JAVA БЭКЕНД
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - ML_CALIBRATOR_URL=http://calibrator:8000/predict
    depends_on:
      - calibrator

  # 3. ML СЛОЙ
  calibrator:
    build:
      context: ./ml/api/calibrator
    ports:
      - "8000:8000"
    # expose:
    #  - "8000" # Порт доступен только внутри сети Docker для Java Бэка
    environment:
      - BERT_URL=http://bert-service:8000/score
      - DETECTGPT_URL=http://detectgpt-service:8000/score
    depends_on:
      - bert-service
      - detectgpt-service

  bert-service:
    build:
      context: ./ml/api/bert_service
    expose:
      - "8000"

  detectgpt-service:
    build:
      context: ./ml/api/detectgpt_service
    expose:
      - "8000"